I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 446, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 446, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 456, in _execute_python_hide
    renpy.load("_reload-2")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 203, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 446, in script
    python hide:
  File "G:\RenPy\1RenPy Core\renpy-7.0.0-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\RenPy\1RenPy Core\renpy-7.0.0-sdk\renpy\python.py", line 1912, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 446, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 456, in _execute_python_hide
    renpy.load("_reload-2")
  File "G:\RenPy\1RenPy Core\renpy-7.0.0-sdk\renpy\loadsave.py", line 728, in load
    log.unfreeze(roots, label="_after_load")
  File "G:\RenPy\1RenPy Core\renpy-7.0.0-sdk\renpy\python.py", line 1867, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "G:\RenPy\1RenPy Core\renpy-7.0.0-sdk\renpy\python.py", line 1696, in rollback
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-8-6.2.9200
Ren'Py 7.0.0.196
Little Slice Of My Life 1.0
Fri Jul 26 18:15:48 2019
